import { useState } from 'react';
import { Download, Loader2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { useToast } from '@/hooks/use-toast';
import html2canvas from 'html2canvas';
import jsPDF from 'jspdf';
import { format } from 'date-fns';
import { ptBR } from 'date-fns/locale';

interface PDFExportProps {
  contentRef: React.RefObject<HTMLDivElement>;
  fileName?: string;
  title?: string;
  subtitle?: string;
  orientation?: 'portrait' | 'landscape';
  quality?: 'normal' | 'high' | 'max';
  includeHeader?: boolean;
  includeFooter?: boolean;
  variant?: 'default' | 'outline' | 'ghost';
  size?: 'default' | 'sm' | 'lg';
  className?: string;
}

export function PDFExport({ 
  contentRef, 
  fileName = 'relatorio',
  title = 'Relatório',
  subtitle,
  orientation = 'portrait',
  quality = 'high',
  includeHeader = true,
  includeFooter = true,
  variant = 'outline',
  size = 'default',
  className,
}: PDFExportProps) {
  const [isExporting, setIsExporting] = useState(false);
  const { toast } = useToast();

  const getScaleForQuality = () => {
    switch (quality) {
      case 'max': return 3;
      case 'high': return 2;
      default: return 1.5;
    }
  };

  const handleExport = async () => {
    if (!contentRef.current) {
      toast({
        title: 'Erro',
        description: 'Conteúdo não encontrado para exportação.',
        variant: 'destructive',
      });
      return;
    }
    
    setIsExporting(true);
    
    try {
      const element = contentRef.current;
      const scale = getScaleForQuality();
      
      // Create canvas with high quality settings
      const canvas = await html2canvas(element, {
        scale,
        useCORS: true,
        logging: false,
        backgroundColor: '#ffffff',
        allowTaint: true,
        imageTimeout: 15000,
      });
      
      const imgData = canvas.toDataURL('image/png', 1.0);
      
      // PDF dimensions based on orientation
      const isLandscape = orientation === 'landscape';
      const pageWidth = isLandscape ? 297 : 210;
      const pageHeight = isLandscape ? 210 : 297;
      
      // Calculate margins
      const marginX = 10;
      const marginTop = includeHeader ? 25 : 10;
      const marginBottom = includeFooter ? 20 : 10;
      
      const contentWidth = pageWidth - (marginX * 2);
      const imgHeight = (canvas.height * contentWidth) / canvas.width;
      const contentHeight = pageHeight - marginTop - marginBottom;

      const pdf = new jsPDF({
        orientation: isLandscape ? 'l' : 'p',
        unit: 'mm',
        format: 'a4',
      });

      // Add metadata
      pdf.setProperties({
        title: title,
        subject: subtitle || 'Relatório exportado',
        author: 'Sistema de Gestão',
        creator: 'PDF Export',
      });

      let heightLeft = imgHeight;
      let position = marginTop;
      let pageNumber = 1;

      const addHeaderFooter = (pageNum: number, totalPages: number) => {
        // Header
        if (includeHeader) {
          pdf.setFillColor(250, 250, 250);
          pdf.rect(0, 0, pageWidth, 20, 'F');
          
          pdf.setFontSize(12);
          pdf.setTextColor(50, 50, 50);
          pdf.text(title, marginX, 12);
          
          if (subtitle) {
            pdf.setFontSize(9);
            pdf.setTextColor(100, 100, 100);
            pdf.text(subtitle, marginX, 17);
          }
          
          // Date on the right
          pdf.setFontSize(8);
          pdf.setTextColor(120, 120, 120);
          const dateText = format(new Date(), "dd/MM/yyyy 'às' HH:mm", { locale: ptBR });
          const dateWidth = pdf.getTextWidth(dateText);
          pdf.text(dateText, pageWidth - marginX - dateWidth, 12);
        }

        // Footer
        if (includeFooter) {
          pdf.setFillColor(250, 250, 250);
          pdf.rect(0, pageHeight - 15, pageWidth, 15, 'F');
          
          pdf.setFontSize(8);
          pdf.setTextColor(120, 120, 120);
          
          const pageText = `Página ${pageNum} de ${totalPages}`;
          const textWidth = pdf.getTextWidth(pageText);
          pdf.text(pageText, (pageWidth - textWidth) / 2, pageHeight - 6);
          
          // Generated by text
          pdf.text('Gerado automaticamente pelo sistema', marginX, pageHeight - 6);
        }
      };

      // Calculate total pages
      const totalPages = Math.ceil(imgHeight / contentHeight);

      // First page
      pdf.addImage(imgData, 'PNG', marginX, position, contentWidth, imgHeight);
      addHeaderFooter(pageNumber, totalPages);
      heightLeft -= contentHeight;
      
      // Additional pages
      while (heightLeft > 0) {
        position = heightLeft - imgHeight + marginTop;
        pdf.addPage();
        pageNumber++;
        pdf.addImage(imgData, 'PNG', marginX, position, contentWidth, imgHeight);
        addHeaderFooter(pageNumber, totalPages);
        heightLeft -= contentHeight;
      }
      
      // Generate filename with date
      const dateStr = format(new Date(), 'yyyy-MM-dd');
      const finalFileName = `${fileName}-${dateStr}.pdf`;
      
      pdf.save(finalFileName);
      
      toast({
        title: 'PDF Exportado!',
        description: `Arquivo "${finalFileName}" salvo com sucesso.`,
      });
    } catch (error) {
      console.error('Error exporting PDF:', error);
      toast({
        title: 'Erro na Exportação',
        description: 'Ocorreu um erro ao gerar o PDF. Tente novamente.',
        variant: 'destructive',
      });
    } finally {
      setIsExporting(false);
    }
  };

  return (
    <Button 
      onClick={handleExport} 
      disabled={isExporting} 
      variant={variant}
      size={size}
      className={className}
    >
      {isExporting ? (
        <>
          <Loader2 className="h-4 w-4 mr-2 animate-spin" />
          Exportando...
        </>
      ) : (
        <>
          <Download className="h-4 w-4 mr-2" />
          Exportar PDF
        </>
      )}
    </Button>
  );
}

// Re-export the dialog component for advanced usage
export { PDFExportDialog } from './PDFExportDialog';
